[web_servers]
app ansible_host=192.168.82.147

[network_services]
wifi ansible_host=192.168.82.148

[storage_servers]
nextcloud ansible_host=192.168.82.149

[homelab:children]
web_servers
network_services
storage_servers

[homelab:vars]
ansible_user=matthew
